profile desktop {
    output "ASUSTek COMPUTER INC ASUS VP249 0x00011745" mode 1920x1080@144.001Hz position 0,0 scale 1
    exec notify-send "kanshi" "Applied kanshi.comfyputer.conf: desktop - ASUS VP249 at 1920x1080@144Hz"
}
