#!/usr/bin/env sh

set -eu

reload=1
if [ "${1:-}" = "--no-reload" ]; then
    reload=0
    shift
fi

mode=auto
case "${1:-}" in
    --mode=light) mode=light; shift ;;
    --mode=dark) mode=dark; shift ;;
    --mode=auto) mode=auto; shift ;;
esac

wallpaper=${1:?usage: apply-wallpaper-theme.sh [--no-reload] [--mode=auto|light|dark] WALLPAPER}
case "$wallpaper" in
    "~"/*) wallpaper="$HOME/${wallpaper#~/}" ;;
esac

if [ "$mode" = "auto" ] && command -v magick >/dev/null 2>&1; then
    brightness=$(magick "$wallpaper" -resize 64x64\! -colorspace Gray -format '%[fx:mean*100]' info:)
    if awk "BEGIN { exit !($brightness >= 42) }"; then
        mode=light
    else
        mode=dark
    fi
elif [ "$mode" = "auto" ]; then
    mode=light
fi

if command -v wal >/dev/null 2>&1; then
    if [ "$mode" = "light" ]; then
        wal -n -q -l -i "$wallpaper"
    else
        wal -n -q -i "$wallpaper"
    fi
    # shellcheck disable=SC1091
    set +u
    . "$HOME/.cache/wal/colors.sh"
    set -u
else
    background="#e8e3d6"
    foreground="#4c4f69"
    cursor="#dc8a78"
    color0="#d2caba"
    color1="#d20f39"
    color2="#40a02b"
    color3="#df8e1d"
    color4="#1e66f5"
    color5="#ea76cb"
    color6="#179299"
    color7="#c8bfad"
    color8="#958b7b"
    color9="#d20f39"
    color10="#40a02b"
    color11="#df8e1d"
    color12="#1e66f5"
    color13="#ea76cb"
    color14="#179299"
    color15="#bdb3a0"
fi

if [ "$mode" = "light" ] && command -v magick >/dev/null 2>&1; then
    paper_bg=$(magick "$wallpaper" -resize 1x1\! -depth 8 -format '%[hex:p{0,0}]' info:)
    paper_bg="#${paper_bg}"
    background=$(magick xc:"$paper_bg" -colorspace HSL -channel B -evaluate set 92% +channel -colorspace sRGB -depth 8 -format '#%[hex:p{0,0}]' info:)
    color0=$(magick xc:"$paper_bg" -colorspace HSL -channel B -evaluate set 86% +channel -colorspace sRGB -depth 8 -format '#%[hex:p{0,0}]' info:)
    color8=$(magick xc:"$paper_bg" -colorspace HSL -channel B -evaluate set 58% +channel -colorspace sRGB -depth 8 -format '#%[hex:p{0,0}]' info:)
fi

sway_config="$HOME/.config/sway/wal.conf"
lock_script="$HOME/.config/sway/scripts/lock.sh"
mako_config="$HOME/.config/mako/config"
zellij_theme="$HOME/.config/zellij/themes/wal.kdl"
ghostty_theme="$HOME/.config/ghostty/themes/wal"
rofi_colors="$HOME/.config/rofi/wal-colors.rasi"
nvim_colors="$HOME/.config/nvim/wal-colors.json"

cat > "$sway_config" <<EOF
# Generated by apply-wallpaper-theme.sh from $wallpaper
# mode=$mode
set \$rosewater $color15
set \$flamingo $color13
set \$pink $color13
set \$mauve $color5
set \$red $color1
set \$maroon $color9
set \$peach $color3
set \$yellow $color11
set \$green $color2
set \$teal $color6
set \$sky $color14
set \$sapphire $color6
set \$blue $color4
set \$lavender $color12
set \$text $foreground
set \$subtext1 $color15
set \$subtext0 $color7
set \$overlay2 $color8
set \$overlay1 $color8
set \$overlay0 $color8
set \$surface2 $color8
set \$surface1 $color7
set \$surface0 $color0
set \$base $background
set \$mantle $color0
set \$crust $color0

output * bg "$wallpaper" fill
EOF

cat > "$lock_script" <<EOF
#!/usr/bin/env sh
# Generated by apply-wallpaper-theme.sh from $wallpaper
# mode=$mode
exec swaylock \\
  --daemonize \\
  --image "$wallpaper" \\
  --scaling fill \\
  --color ${background#\#} \\
  --inside-color ${background#\#} \\
  --ring-color ${color8#\#} \\
  --line-color ${background#\#} \\
  --key-hl-color ${color2#\#} \\
  --bs-hl-color ${color1#\#} \\
  --separator-color ${background#\#} \\
  --text-color ${foreground#\#}
EOF
chmod +x "$lock_script"

if [ -f "$mako_config" ]; then
    tmp="${mako_config}.tmp"
    awk \
        -v bg="$background" \
        -v fg="$foreground" \
        -v border="$color8" \
        -v progress="$color4" \
        -v critical="$color1" '
        /^background-color=/ { print "background-color=" bg; next }
        /^text-color=/ { print "text-color=" fg; next }
        /^border-color=/ && !critical_section { print "border-color=" border; next }
        /^progress-color=/ { print "progress-color=over " progress; next }
        /^\[urgency=critical\]/ { critical_section = 1; print; next }
        critical_section && /^border-color=/ { print "border-color=" critical; next }
        { print }
    ' "$mako_config" > "$tmp"
    mv "$tmp" "$mako_config"
    makoctl reload >/dev/null 2>&1 || true
fi

cat > "$zellij_theme" <<EOF
// Generated by apply-wallpaper-theme.sh from $wallpaper
// mode=$mode
themes {
  wal {
    bg "$background"
    fg "$foreground"
    red "$color1"
    green "$color2"
    blue "$color4"
    yellow "$color3"
    magenta "$color5"
    orange "$color9"
    cyan "$color6"
    black "$background"
    white "$foreground"
  }
}
EOF

cat > "$ghostty_theme" <<EOF
# Generated by apply-wallpaper-theme.sh from $wallpaper
# mode=$mode
palette = 0=${color0}
palette = 1=${color1}
palette = 2=${color2}
palette = 3=${color3}
palette = 4=${color4}
palette = 5=${color5}
palette = 6=${color6}
palette = 7=${color7}
palette = 8=${color8}
palette = 9=${color9}
palette = 10=${color10}
palette = 11=${color11}
palette = 12=${color12}
palette = 13=${color13}
palette = 14=${color14}
palette = 15=${color15}
background = ${background#\#}
foreground = ${foreground#\#}
cursor-color = ${cursor#\#}
cursor-text = ${background#\#}
selection-background = ${color8#\#}
selection-foreground = ${foreground#\#}
EOF

cat > "$rofi_colors" <<EOF
/* Generated by apply-wallpaper-theme.sh from $wallpaper
 * mode=$mode
 */
* {
    bg: ${background}f2;
    bg-solid: ${background};
    surface: ${color0};
    surface2: ${color8};
    border: ${color8};
    text: ${foreground};
    muted: ${color7};
    accent: ${color4};
    urgent: ${color1};
}
EOF

cat > "$nvim_colors" <<EOF
{
  "mode": "$mode",
  "wallpaper": "$wallpaper",
  "special": {
    "background": "$background",
    "foreground": "$foreground",
    "cursor": "$cursor"
  },
  "colors": {
    "color0": "$color0",
    "color1": "$color1",
    "color2": "$color2",
    "color3": "$color3",
    "color4": "$color4",
    "color5": "$color5",
    "color6": "$color6",
    "color7": "$color7",
    "color8": "$color8",
    "color9": "$color9",
    "color10": "$color10",
    "color11": "$color11",
    "color12": "$color12",
    "color13": "$color13",
    "color14": "$color14",
    "color15": "$color15"
  }
}
EOF

swaymsg output '*' bg "$wallpaper" fill >/dev/null 2>&1 || true

if [ "$reload" -eq 1 ]; then
    swaymsg reload >/dev/null 2>&1 || true
fi
