#!/usr/bin/env sh
# Generated by apply-wallpaper-theme.sh from /home/teo/.config/wallpapers/tiefighter.jpeg
# mode=light
exec swaylock \
  --daemonize \
  --image "/home/teo/.config/wallpapers/tiefighter.jpeg" \
  --scaling fill \
  --color E9EBEC \
  --inside-color E9EBEC \
  --ring-color 8E989A \
  --line-color E9EBEC \
  --key-hl-color 76898F \
  --bs-hl-color 6B7A85 \
  --separator-color E9EBEC \
  --text-color 3d3d3c
