#!/usr/bin/env sh
# Generated by apply-wallpaper-theme.sh from /home/teo/.config/wallpapers/kenobimandalore.jpg
# mode=dark
exec swaylock \
  --daemonize \
  --image "/home/teo/.config/wallpapers/kenobimandalore.jpg" \
  --scaling fill \
  --color 1f0d0d \
  --inside-color 1f0d0d \
  --ring-color 715c5c \
  --line-color 1f0d0d \
  --key-hl-color 9E654F \
  --bs-hl-color DA5D27 \
  --separator-color 1f0d0d \
  --text-color c7c2c2
