[package]
    [package."$"]
        [package."$".python]
        [package."$".kitty]
        [package."$".ranger]
        [package."$".w3m]
        [package."$".picom]
        [package."$".fish]
        [package."$".imagemagick]
        [package."$".neovim]
        [package."$".firefox]
        [package."$".flameshot]
        [package."$".pipewire]
        [package."$".dunst]
        [package."$".dmenu]
        [package."$".i3]
        [package."$".acpi]
        [package."$".rustup]
        [package."$".zathura]
        [package."$".hugo]
        [package."$".git]

    [package.pacman]
        [package.pacman.pamixer]

    [package.cargo]
        [package.cargo.ripgrep]
        [package.cargo.bat]
        [package.cargo.exa]
