# mehr config, see https://github.com/xNaCly/mehr
package-manager = "auto"

[git]
# git config --global credential.helper store
# git config --global user.name "xnacly"
# git config --global user.email "47723417+xNaCly@users.noreply.github.com"

# default packages i require
[package]
    [package."$".i3]
    [package."$".python]
    [package."$".dunst]
    [package."$".kitty]
    [package."$".ranger]
    [package."$".w3m]
    [package."$".picom]
    [package."$".fish]
    [package."$".imagemagick]
    [package."$".neovim]
    [package."$".firefox]
    [package."$".flameshot]
    [package."$".pipewire]
    [package."$".pamixer]
    [package."$".exa]
    [package."$".dmenu]

[config]
path = "/home/teo/.config"
