
#██╗  ██╗███╗   ██╗ █████╗  ██████╗██╗  ██╗   ██╗███████╗    ██╗██████╗      ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ 
#╚██╗██╔╝████╗  ██║██╔══██╗██╔════╝██║  ╚██╗ ██╔╝██╔════╝    ██║╚════██╗    ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ 
# ╚███╔╝ ██╔██╗ ██║███████║██║     ██║   ╚████╔╝ ███████╗    ██║ █████╔╝    ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
# ██╔██╗ ██║╚██╗██║██╔══██║██║     ██║    ╚██╔╝  ╚════██║    ██║ ╚═══██╗    ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
#██╔╝ ██╗██║ ╚████║██║  ██║╚██████╗███████╗██║   ███████║    ██║██████╔╝    ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
#╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝ ╚═════╝╚══════╝╚═╝   ╚══════╝    ╚═╝╚═════╝      ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝ 

general {
        colors = true
        interval = 1
        color_good = "#CCB2B2"
        color_bad = "#6B748A"
        color_degraded = "#6B748A"
}

#order += "ipv6"
order += "wireless _first_"
order += "ethernet _first_"
#order += "disk /"
#order += "load"
order += "cpu_usage"
order += "memory"
#order += "battery all"
order += "volume master"
order += "tztime local"

wireless _first_ {
        format_up = "直 "
        format_down = "睊 "
}

ethernet _first_ {
        format_up = " "
        format_down = " "
}

battery all {
        format = "%status %percentage"
        status_chr = ""
        status_bat = ""
        status_unk = ""
        status_full = ""
        low_threshold = 25
}

disk "/" {
        format = "%avail"
}

load {
        format = "%1min"
}

memory {
        format = " %used"
        threshold_degraded = "1G"
        format_degraded = "MEMORY < %available"
}

tztime local {
        format = " %d.%m %H:%M:%S "
}

cpu_usage {
        format = " %usage"
}

volume master {
        format = " %volume"
        format_muted = " --%"
        device = "pulse"
}

